<%@ Page Title="Blog | Communications Technologies Inc." Language="C#" MasterPageFile="/masterpage.master" %>


<asp:Content ID="head" ContentPlaceHolderID="cphHead" runat="server">

    <link rel="stylesheet" href="https://code.a8b.co/blog/style.css" />

</asp:Content>

<asp:Content ID="content" ContentPlaceHolderID="cphMain" runat="Server">
    <section>
                
    <h1>Blog</h1>
    <div id="blogs"><div id="blogsidebar"><h3>Categories</h3><ul><li><a href="/blog.aspx?p=about-us">About Us</a></li><li><a href="/blog.aspx?p=business-phone">Business Phone</a></li><li><a href="/blog.aspx?p=business-solutions">Business Solutions</a></li><li><a href="/blog.aspx?p=case-studies">Case studies</a></li><li><a href="/blog.aspx?p=community-involvement">Community Involvement</a></li><li><a href="/blog.aspx?p=data-recovery">Data Recovery</a></li><li><a href="/blog.aspx?p=managed-solutions">Managed Solutions</a></li><li><a href="/blog.aspx?p=news">News</a></li><li><a href="/blog.aspx?p=press-release">Press Release</a></li><li><a href="/blog.aspx?p=products">Products</a></li><li><a href="/blog.aspx?p=projects">Projects</a></li><li><a href="/blog.aspx?p=security">Security</a></li><li><a href="/blog.aspx?p=services">Services</a></li><li><a href="/blog.aspx?p=solutions">Solutions</a></li><li><a href="/blog.aspx?p=testimonials">Testimonials</a></li><li><a href="/blog.aspx?p=uncategorized">Uncategorized</a></li><li><a href="/blog.aspx?p=unified-communications-">Unified Communications </a></li></ul><h3>Archives</h3><ul><li><a href="/blog.aspx?p=2019">2019</a></li><li><a href="/blog.aspx?p=2018">2018</a></li><li><a href="/blog.aspx?p=2017">2017</a></li><li><a href="/blog.aspx?p=2016">2016</a></li><li><a href="/blog.aspx?p=2015">2015</a></li><li><a href="/blog.aspx?p=2014">2014</a></li><li><a href="/blog.aspx?p=2013">2013</a></li><li><a href="/blog.aspx?p=2012">2012</a></li><li><a href="/blog.aspx?p=2011">2011</a></li></ul></div><div id="posts"><div class="post"><h2><a href="/blog.aspx?p=how-our-fully-managed-it-services-can-help-your-business-focus-on-whats-important-190619">How our Fully-Managed IT Services can Help Your Business Focus on What's Important</a></h2><p>June 19th, 2019 by admin</p><p>

    What does your business do? Seems like a simple question with an easy answer, but when you really break it down by time and resources spent it becomes more complicated. How much of those two things are actually spent on what's important to your business, and how much of it is wasted on managing...</p><p><a href="/blog.aspx?p=how-our-fully-managed-it-services-can-help-your-business-focus-on-whats-important-190619">Read Full Story&nbsp;»</a></p><p class="posttags">Tags: <a href="/blog.aspx?p=it">IT</a>, <a href="/blog.aspx?p=managed-services">managed services</a>, <a href="/blog.aspx?p=it-management">IT management</a>, <a href="/blog.aspx?p=network">network</a>, <a href="/blog.aspx?p=it-solutions">IT solutions</a>, <a href="/blog.aspx?p=business-continuity">business continuity</a>, </p><p class="postcats">Posted in: <a href="/blog.aspx?p=solutions">Solutions</a>, </p></div><div class="post"><h2><a href="/blog.aspx?p=cti-advises-businesses-to-move-to-the-cloud-with-microsoft-azure--190611">CTI Advises Businesses to Move to the Cloud with Microsoft Azure </a></h2><p>June 11th, 2019 by admin</p><p>
BURTON, MI – 
We are advising small and mid-sized businesses (SMBs) to move to Microsoft Azure as soon as possible. With Windows 7 expiring at the end of this year, SMBs need to act quickly in order to ensure that their transition goes smoothly and without interruption to their business. There...</p><p><a href="/blog.aspx?p=cti-advises-businesses-to-move-to-the-cloud-with-microsoft-azure--190611">Read Full Story&nbsp;»</a></p><p class="posttags">Tags: <a href="/blog.aspx?p=microsoft-certified-partner">Microsoft certified partner</a>, <a href="/blog.aspx?p=communications-technologies">Communications Technologies</a>, <a href="/blog.aspx?p=solutions">solutions</a>, <a href="/blog.aspx?p=cloud-based">cloud-based</a>, </p><p class="postcats">Posted in: <a href="/blog.aspx?p=press-release">Press Release</a>, </p></div><div class="post"><h2><a href="/blog.aspx?p=unique-uses-of-surveillance-systems-in-your-business-190514">Unique Uses of Surveillance Systems in Your Business</a></h2><p>May 14th, 2019 by admin</p><p> 

    Video monitoring and surveillance, while extremely important, aren't only for catching the bad guys. Every company needs some form of surveillance system that is tailored for their type of business, whether it be a surveillance system for a factory or plant or a monitoring system for an agricultural...</p><p><a href="/blog.aspx?p=unique-uses-of-surveillance-systems-in-your-business-190514">Read Full Story&nbsp;»</a></p><p class="posttags">Tags: <a href="/blog.aspx?p=surveillance">surveillance</a>, <a href="/blog.aspx?p=video">video</a>, <a href="/blog.aspx?p=mobile-access">mobile access</a>, <a href="/blog.aspx?p=cameras">cameras</a>, </p><p class="postcats">Posted in: <a href="/blog.aspx?p=solutions">Solutions</a>, </p></div><div class="post"><h2><a href="/blog.aspx?p=cti-offers-sd-wan-as-a-service-to-smbs-190508">CTI Offers SD-WAN-as-a-Service to SMBs</a></h2><p>May 8th, 2019 by admin</p><p>
BURTON, MI – CTI
a leading managed technology
services provider (MTSP),
announced today that the
company now offers SD-WAN-as-a-Service to their small to midsized business (SMB) customers.
SD-WAN is a leading technology
and according to research firm
Gartner, “by the end of 2019,
30% of enterprises...</p><p><a href="/blog.aspx?p=cti-offers-sd-wan-as-a-service-to-smbs-190508">Read Full Story&nbsp;»</a></p><p class="posttags">Tags: <a href="/blog.aspx?p=technology">technology</a>, <a href="/blog.aspx?p=managed-services">managed services</a>, <a href="/blog.aspx?p=sd-wan">SD-WAN</a>, <a href="/blog.aspx?p=network">network</a>, </p><p class="postcats">Posted in: <a href="/blog.aspx?p=press-release">Press Release</a>, </p></div><div class="post"><h2><a href="/blog.aspx?p=cti-educates-smbs-on-surveillance--security-breakthrough--190413">CTI Educates SMBs on  Surveillance &amp; Security Breakthrough </a></h2><p>April 13th, 2019 by admin</p><p>

 BURTON, MI – March 2019 – Communications Technologies, Inc. (CTI), a leading managed technology services provider (MTSP), is helping small to mid-sized businesses (SMBs) to take advantage of dramatically increased capabilities in surveillance cameras. As security, both online and offline,...</p><p><a href="/blog.aspx?p=cti-educates-smbs-on-surveillance--security-breakthrough--190413">Read Full Story&nbsp;»</a></p><p class="posttags">Tags: <a href="/blog.aspx?p=technology">technology</a>, <a href="/blog.aspx?p=press-release">Press Release</a>, <a href="/blog.aspx?p=security">security</a>, <a href="/blog.aspx?p=video">video</a>, </p><p class="postcats">Posted in: <a href="/blog.aspx?p=press-release">Press Release</a>, </p></div><div class="post"><h2><a href="/blog.aspx?p=3-major-reasons-why-your-business-needs-firewall-as-a-service-fwaas-190412">3 Major Reasons Why Your Business Needs Firewall as a Service (FWaaS)</a></h2><p>April 12th, 2019 by admin</p><p>

Known as “next generation firewall” is a firewall in a cloud service that is used to protect users on the internet. For businesses on private clouds and networks, it has become all the rage due to the enhanced security capabilities. No longer is there a need for firewall appliances or vulnerable network...</p><p><a href="/blog.aspx?p=3-major-reasons-why-your-business-needs-firewall-as-a-service-fwaas-190412">Read Full Story&nbsp;»</a></p><p class="posttags">Tags: <a href="/blog.aspx?p=services">services</a>, <a href="/blog.aspx?p=anti-virus-threat">anti-virus threat</a>, <a href="/blog.aspx?p=cyber-security">cyber security</a>, <a href="/blog.aspx?p=firewall">firewall</a>, </p><p class="postcats">Posted in: <a href="/blog.aspx?p=security">Security</a>, </p></div><div class="post"><h2><a href="/blog.aspx?p=communications-technologies-inc-cti-to-share-technology-expertise-at-the-technology-assurance-group-2019-annual-convention-190316">Communications Technologies, Inc. (CTI) to Share Technology Expertise at The Technology Assurance Group 2019 Annual Convention</a></h2><p>March 16th, 2019 by admin</p><p>

 BURTON, MI – February 2019 – Communications Technologies, Inc. (CTI), a leading managed technology services provider (MTSP), announced today that they have been invited to attend the 19th Annual Technology Assurance Group (TAG) convention in Orlando, Florida. The event will take place...</p><p><a href="/blog.aspx?p=communications-technologies-inc-cti-to-share-technology-expertise-at-the-technology-assurance-group-2019-annual-convention-190316">Read Full Story&nbsp;»</a></p><p class="posttags">Tags: <a href="/blog.aspx?p=cti">CTI</a>, <a href="/blog.aspx?p=advanced-technology">Advanced Technology</a>, <a href="/blog.aspx?p=press-release">Press Release</a>, <a href="/blog.aspx?p=communications-technologies">Communications Technologies</a>, <a href="/blog.aspx?p=solutions">solutions</a>, <a href="/blog.aspx?p=tag-annual-convention">TAG Annual Convention</a>, </p><p class="postcats">Posted in: <a href="/blog.aspx?p=press-release">Press Release</a>, </p></div><div class="post"><h2><a href="/blog.aspx?p=cti-celebrates-merger-with-pro-tech-communications-190307">CTI Celebrates Merger with Pro-Tech Communications</a></h2><p>March 7th, 2019 by admin</p><p>
  
 
BURTON, MI – We have merged with ProTech Communications, a voice services company, in order to expand CTI’s abilities to serve its customers even better. Jeff Allen, President of CTI, has been working very closely with both Gary Antrobius and Richard Stewart over the past several months in...</p><p><a href="/blog.aspx?p=cti-celebrates-merger-with-pro-tech-communications-190307">Read Full Story&nbsp;»</a></p><p class="posttags">Tags: <a href="/blog.aspx?p=communications">Communications</a>, <a href="/blog.aspx?p=cti">CTI</a>, <a href="/blog.aspx?p=news">news</a>, <a href="/blog.aspx?p=customer-satisfaction">customer satisfaction</a>, </p><p class="postcats">Posted in: <a href="/blog.aspx?p=press-release">Press Release</a>, </p></div><div class="post"><h2><a href="/blog.aspx?p=protecting-businesses-from-windows-7-end-of-life-190205">Protecting Businesses from Windows 7 End of Life</a></h2><p>February 5th, 2019 by admin</p><p>
  
     BURTON, MI –
        We are helping small to mid-sized businesses (SMBs) secure their organizations from cyber-attacks by addressing the Windows 7 "End of Life" policy that will begin in January of 2020. Microsoft has announced that they will cease supporting the software, providing updates,...</p><p><a href="/blog.aspx?p=protecting-businesses-from-windows-7-end-of-life-190205">Read Full Story&nbsp;»</a></p><p class="posttags">Tags: <a href="/blog.aspx?p=it">IT</a>, <a href="/blog.aspx?p=security">security</a>, <a href="/blog.aspx?p=cyber-security">cyber security</a>, <a href="/blog.aspx?p=solutions">solutions</a>, </p><p class="postcats">Posted in: <a href="/blog.aspx?p=press-release">Press Release</a>, </p></div><div class="post"><h2><a href="/blog.aspx?p=protection-for-our-schools-190129">Protection for Our Schools</a></h2><p>January 29th, 2019 by admin</p><p> 
    
        With the current social climate and constant fear of danger, everyone agrees that schools need to have enhanced security to keep our children safe and out of harm's way. As technology evolves, we are coming up with new and innovative solutions to both on and off-site security. 
    
 ...</p><p><a href="/blog.aspx?p=protection-for-our-schools-190129">Read Full Story&nbsp;»</a></p><p class="posttags">Tags: <a href="/blog.aspx?p=technology">technology</a>, <a href="/blog.aspx?p=security">security</a>, <a href="/blog.aspx?p=surveillance">surveillance</a>, <a href="/blog.aspx?p=cameras">cameras</a>, </p><p class="postcats">Posted in: <a href="/blog.aspx?p=solutions">Solutions</a>, </p></div></div></div>

    



            </section>
 <uc:blog domain="http://blog.cti4u.lamp.a8b.co/" />

</asp:Content>
